package com.bjpowernode.p2p.mapper.loan;


import com.bjpowernode.p2p.model.loan.BidInfo;

import java.util.List;
import java.util.Map;

public interface BidInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Aug 12 20:38:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Aug 12 20:38:47 CST 2019
     */
    int insert(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Aug 12 20:38:47 CST 2019
     */
    int insertSelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Aug 12 20:38:47 CST 2019
     */
    BidInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Aug 12 20:38:47 CST 2019
     */
    int updateByPrimaryKeySelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Aug 12 20:38:47 CST 2019
     */
    int updateByPrimaryKey(BidInfo record);

    /**
     * @author Administrator
     * @description
     * @date 2019/8/14
     * @param
     * @method selectAllBidMoney  查询累计成交金额
     * @return java.lang.Double
     **/
    Double selectAllBidMoney();

    /**
     * 分页查询投标信息表
     * @param paramMap 用户id 掠过的记录数 每页展示的数据
     * @return 投标信息列表
     */
    List<BidInfo> queryRecentlyBidInfoList(Map<String, Object> paramMap);

    /**
     * 通过投标产品的id来查询所对应的用户投资信息表
     * @param paramMap 数组 包含掠过的记录数 每页展示的记录数 投标产品的id
     * @return 投标产品列表
     */
    List<BidInfo> selectRecentlyBidInfoListByLoanId(Map<String, Object> paramMap);
}