package com.bjpowernode.p2p.mapper.loan;


import com.bjpowernode.p2p.model.loan.LoanInfo;

import java.util.List;
import java.util.Map;

public interface LoanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Mon Aug 12 20:38:46 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Mon Aug 12 20:38:46 CST 2019
     */
    int insert(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Mon Aug 12 20:38:46 CST 2019
     */
    int insertSelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Mon Aug 12 20:38:46 CST 2019
     */
    LoanInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Mon Aug 12 20:38:46 CST 2019
     */
    int updateByPrimaryKeySelective(LoanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_loan_info
     *
     * @mbggenerated Mon Aug 12 20:38:46 CST 2019
     */
    int updateByPrimaryKey(LoanInfo record);

    /**
     * @author Administrator
     * @description 获取历史年华收益
     * @date 2019/8/13
     * @param
     * @method selectHistoryAverageRate
     * @return java.lang.Double
     **/
    Double selectHistoryAverageRate();

    /**
     * @author Administrator
     * @description
     * @date 2019/8/15
     * @param paramMap 页码 产品类型
     * @method selectLoadInfoListByProductType
     * @return java.util.List<com.bjpowernode.p2p.model.loan.LoanInfo>
     **/
    List<LoanInfo> selectLoadInfoListByProductType(Map<String, Object> paramMap);

    /**
     * @author Administrator
     * @description
     * @date 2019/8/16
     * @param paramMap 获取产品的总计录数
     * @method selectTotal
     * @return java.lang.Long
     **/
    Long selectTotal(Map<String, Object> paramMap);
}