package com.bjpowernode.p2p.mapper.user;

import com.bjpowernode.p2p.model.user.FinanceAccount;

import java.util.Map;

public interface FinanceAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Aug 12 20:38:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Aug 12 20:38:47 CST 2019
     */
    int insert(FinanceAccount record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Aug 12 20:38:47 CST 2019
     */
    int insertSelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Aug 12 20:38:47 CST 2019
     */
    FinanceAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Aug 12 20:38:47 CST 2019
     */
    int updateByPrimaryKeySelective(FinanceAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_finance_account
     *
     * @mbggenerated Mon Aug 12 20:38:47 CST 2019
     */
    int updateByPrimaryKey(FinanceAccount record);

    /**
     *
     * @param id 用户的id
     * @return FinanceAccount 用户的资金
     */
    FinanceAccount selectFinanceAccountByUid(Integer id);

    /**
     * 充值充值是更新账户余额
     * @param rechargeMap
     * @return
     */
    int updateFinanceAccountByRecharge(Map<String, Object> rechargeMap);
}